### ISSUE TITLE
Uncaught TypeError: this.getRecaptcha is not a function

### ISSUE THREAD

**Issue by Ephasme** [DanSnow/vue-recaptcha#30] opened 2017-01-15 22:30 UTC
I carefully followed your steps for installation but I keep getting this error.
I have done nothing special. Inserted the tag in the head, added VueRecaptcha as a component and put the key in the key attribute.

What do you need from me in order to debug this?

**Comment by DanSnow** [comment] 2017-01-16 03:24
Can you provide a jsbin or jsfiddle to reproduce?
Or a gist if you are using vue-recaptcha from npm.
Thanks.

**Comment by DanSnow** [comment] 2017-01-16 10:08
I have try some possible ways, but I can't reproduce this error.
But I noticed that my document is outdated. Prop `key` have been renamed to `sitekey`.

**Comment by CinKon** [comment] 2017-01-20 07:31
Got the same error...

**Comment by Ephasme** [comment] 2017-01-20 07:34
I'll give you a gist asap

**Comment by hybaken** [comment] 2017-01-20 13:45
Got the same problem...

**Comment by DanSnow** [comment] 2017-01-31 07:29
@Ephasme @CinKon @hybaken 
Hello, I really need somebody help me to reproduce this.
Or I can't fix it.

**Comment by jzelez** [comment] 2017-02-04 10:13
There appears to be a problem with the npm version of the package.
When installing directly from github (`yarn add github:DanSnow/vue-recaptcha`), it works just fine.

**Comment by DanSnow** [comment] 2017-02-04 11:13
@jzelez 
Got it. Thanks.
But I still can't get this error.

I think I can just change the main script in `package.json` to `dist/vue-recaptcha.js`.

**Comment by jzelez** [comment] 2017-02-04 12:47
I've tested it some more. It isn't an issue with npm or anything... Sorry for false alarm.
The problem is definitely package.json pointing to a wrong file. Fix that, publish new version and all is good in the world. ;)

**Comment by DanSnow** [comment] 2017-02-04 13:16
OK. I've published v0.3.1.

**Comment by jzelez** [comment] 2017-02-04 13:36
There is now a problem when installing:

```
❯ yarn add vue-recaptcha
yarn add v0.18.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/vue-recaptcha/-/vue-recaptcha-0.3.1.tgz: invalid tar file".


❯ npm install vue-recaptcha
npm ERR! cb() never called!
```

**Comment by DanSnow** [comment] 2017-02-04 14:28
Oh. Maybe I shouldn't use yarn to publish it.

**Comment by DanSnow** [comment] 2017-02-04 14:38
I don't know why the tarball on npm is corrupt.
I publish it again with version `0.3.2`.
And I have tested it. It should work.

**Comment by jzelez** [comment] 2017-02-04 14:51
Hmm.. now it installs, but gives the previous error `Uncaught TypeError: this.getRecaptcha is not a function` when using `import VueRecaptcha from 'vue-recaptcha'`.
If I changed it back to your compiled version (`import VueRecaptcha from 'vue-recaptcha/dist/vue-recaptcha'`) then it works.

Package.json now points to main.js, which apparently doesn't compile as it should. I think you should point `main` to `dist/vue-recaptcha.js`.

**Comment by DanSnow** [comment] 2017-02-04 15:02
But I have change the entry point to `dist/vue-recaptcha.js
Here is  [package.json](https://unpkg.com/vue-recaptcha@0.3.2/package.json) on unpkg. 
Can you check which version you installed?

**Comment by jzelez** [comment] 2017-02-04 17:33
Yup. It works now.. Seems yarn messed up my local cache. Sorry about that :)

Thanks! 👍

**Comment by DanSnow** [comment] 2017-02-05 01:21
OK. I'll close this issue.

**Closed by DanSnow** 2017-02-05 01:21 UTC
